### ISSUE TITLE
mp4 box parse

### ISSUE THREAD

**Issue by grylem** [Hell0wor1d/youkuMP4Patcher#1]
sorry for the indelicate question: what software are you using to view mp4 atoms tree?
from you blog post https://kev7n.com/2015/09/12/yk-mp4-patcher/

![](https://kev7n.com/content/images/2015/09/2011101710133455.jpg)

**Comment by Hell0wor1d** [comment]
actually this screenshot is an excel file, how about this tool ? [mp4 viewer](https://archive.codeplex.com/?p=mp4explorer).

**Comment by grylem** [comment]
Thanks. For macOS 
https://github.com/joconor/atomicviewer

**Comment by Hell0wor1d** [comment]
you are welcome :-)
